export const images = {
  arrowDown: require('../assets/icons/arrow_down.svg').default,
  arrowLeft: require('../assets/icons/arrow_left.svg').default,
  arrowRight: require('../assets/icons/arrow_right.svg').default,
  hamburgerMenu: require('../assets/icons/hamburger_menu.svg').default,
  add: require('../assets/icons/add.svg').default,
  arrowUp: require('../assets/icons/arrow_up.svg').default,
  calender: require('../assets/icons/calender.svg').default,
  check: require('../assets/icons/check.svg').default,
  checkActive: require('../assets/icons/check_active.svg').default,
  claim: require('../assets/icons/claims.svg').default,
  close: require('../assets/icons/close.svg').default,
  copy: require('../assets/icons/copy.svg').default,
  darkMode: require('../assets/icons/darkMode.svg').default,
  dashboard: require('../assets/icons/dashboard.svg').default,
  dayMode: require('../assets/icons/dayMode.svg').default,
  discord: require('../assets/icons/discord.svg').default,
  discordFull: require('../assets/icons/discord-full.svg').default,
  edit: require('../assets/icons/edit.svg').default,
  externalLink: require('../assets/icons/external_link.svg').default,
  feedback: require('../assets/icons/feedback.svg').default,
  github: require('../assets/icons/github.svg').default,
  google: require('../assets/icons/google.svg').default,
  guarding: require('../assets/icons/guarding.svg').default,
  heart: require('../assets/icons/heart.svg').default,
  info: require('../assets/icons/info.svg').default,
  infoActive: require('../assets/icons/info_active.svg').default,
  inherit: require('../assets/icons/inherit.svg').default,
  lock: require('../assets/icons/lock.svg').default,
  locked: require('../assets/icons/locked.svg').default,
  metaMask: require('../assets/icons/metamask.svg').default,
  money: require('../assets/icons/money.svg').default,
  notification: require('../assets/icons/notification.svg').default,
  profile: require('../assets/icons/profile.svg').default,
  safes: require('../assets/icons/safes.svg').default,
  twitter: require('../assets/icons/twitter.svg').default,
  upload: require('../assets/icons/upload.svg').default,
  bitcoin: require('../assets/icons/bitcoin.svg').default,
  ether: require('../assets/icons/ether.svg').default,
  error: require('../assets/icons/error.svg').default,
  checkSuccess: require('../assets/icons/checkSuccess.svg').default,
  safientAvatar: require('../assets/logo/safient_avatar.png').default,
  LoginWithGoogle: require('../assets/icons/login-google.svg').default,
  LoginWithGitHub: require('../assets/icons/login-github.svg').default,
  LoginWithMetaMask: require('../assets/icons/login-metamask.svg').default,
};

export type Images = typeof images;
export type Image = keyof typeof images;
