export const images = {
  arrowDown: require('../assets/icons/arrow_down.svg'),
  arrowLeft: require('../assets/icons/arrow_left.svg'),
  arrowRight: require('../assets/icons/arrow_right.svg'),
  hamburgerMenu: require('../assets/icons/hamburger_menu.svg'),
  add: require('../assets/icons/add.svg'),
  arrowUp: require('../assets/icons/arrow_up.svg'),
  calender: require('../assets/icons/calender.svg'),
  check: require('../assets/icons/check.svg'),
  checkActive: require('../assets/icons/check_active.svg'),
  claim: require('../assets/icons/claims.svg'),
  close: require('../assets/icons/close.svg'),
  copy: require('../assets/icons/copy.svg'),
  darkMode: require('../assets/icons/darkMode.svg'),
  dashboard: require('../assets/icons/dashboard.svg'),
  dayMode: require('../assets/icons/dayMode.svg'),
  discord: require('../assets/icons/discord.svg'),
  discordFull: require('../assets/icons/discord-full.svg'),
  edit: require('../assets/icons/edit.svg'),
  externalLink: require('../assets/icons/external_link.svg'),
  feedback: require('../assets/icons/feedback.svg'),
  github: require('../assets/icons/github.svg'),
  google: require('../assets/icons/google.svg'),
  guarding: require('../assets/icons/guarding.svg'),
  heart: require('../assets/icons/heart.svg'),
  info: require('../assets/icons/info.svg'),
  infoActive: require('../assets/icons/info_active.svg'),
  inherit: require('../assets/icons/inherit.svg'),
  lock: require('../assets/icons/lock.svg'),
  locked: require('../assets/icons/locked.svg'),
  metaMask: require('../assets/icons/metamask.svg'),
  money: require('../assets/icons/money.svg'),
  notification: require('../assets/icons/notification.svg'),
  profile: require('../assets/icons/profile.svg'),
  safes: require('../assets/icons/safes.svg'),
  twitter: require('../assets/icons/twitter.svg'),
  upload: require('../assets/icons/upload.svg'),
};

export type ImageTypes = keyof typeof images;
